In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn import metrics

In [2]:
D = pd.read_csv("diabetes.csv")
D

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
feature_cols = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]
X = D[feature_cols].values
Y = D.Outcome

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.25, random_state=42)

In [5]:
X_train

array([[ 13.   , 129.   ,   0.   , ...,  39.9  ,   0.569,  44.   ],
       [  4.   , 129.   ,  86.   , ...,  35.1  ,   0.231,  23.   ],
       [  3.   ,  61.   ,  82.   , ...,  34.4  ,   0.243,  46.   ],
       ...,
       [ 10.   , 101.   ,  86.   , ...,  45.6  ,   1.136,  38.   ],
       [  0.   , 141.   ,   0.   , ...,  42.4  ,   0.205,  29.   ],
       [  0.   , 125.   ,  96.   , ...,  22.5  ,   0.262,  21.   ]])

In [6]:
X_test

array([[  6.   ,  98.   ,  58.   , ...,  34.   ,   0.43 ,  43.   ],
       [  2.   , 112.   ,  75.   , ...,  35.7  ,   0.148,  21.   ],
       [  2.   , 108.   ,  64.   , ...,  30.8  ,   0.158,  21.   ],
       ...,
       [  6.   , 123.   ,  72.   , ...,  33.6  ,   0.733,  34.   ],
       [  3.   ,  78.   ,  50.   , ...,  31.   ,   0.248,  26.   ],
       [  3.   , 106.   ,  72.   , ...,  25.8  ,   0.207,  27.   ]])

In [7]:
Y_train

357    1
73     0
352    0
497    0
145    0
      ..
71     0
106    0
270    1
435    1
102    0
Name: Outcome, Length: 576, dtype: int64

In [8]:
Y_test

668    0
324    0
624    0
690    0
473    0
      ..
554    0
319    1
594    0
6      1
615    0
Name: Outcome, Length: 192, dtype: int64

In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 2.80346794,  0.25977903, -3.78077929, ...,  1.03974028,
         0.29608546,  0.96352088],
       [ 0.07832678,  0.25977903,  0.89724451, ...,  0.40945373,
        -0.70087555, -0.86295593],
       [-0.22446668, -1.85825286,  0.67966201, ...,  0.31753694,
        -0.66548048,  1.13747105],
       ...,
       [ 1.89508755, -0.61235174,  0.89724451, ...,  1.78820556,
         1.96850229,  0.44167036],
       [-1.13284707,  0.63354937, -3.78077929, ...,  1.36801453,
        -0.77756486, -0.34110542],
       [-1.13284707,  0.13518892,  1.44120077, ..., -1.24504846,
        -0.6094383 , -1.03690611]])

In [11]:
X_test

array([[ 0.6839137 , -0.70579433, -0.625833  , ...,  0.26501306,
        -0.11390738,  0.87654579],
       [-0.52726014, -0.26972894,  0.29889263, ...,  0.48823955,
        -0.94569142, -1.03690611],
       [-0.52726014, -0.39431905, -0.29945925, ..., -0.15517797,
        -0.91619553, -1.03690611],
       ...,
       [ 0.6839137 ,  0.07289387,  0.13570575, ...,  0.21248918,
         0.77981801,  0.09377001],
       [-0.22446668, -1.32874488, -1.06099801, ..., -0.12891603,
        -0.65073254, -0.60203068],
       [-0.22446668, -0.45661411,  0.13570575, ..., -0.81172646,
        -0.77166568, -0.51505559]])

In [12]:
#Algorithm- Model
LR= LogisticRegression(random_state=42)
LR.fit(X_train, Y_train)


from sklearn.neighbors import KNeighborsClassifier
KN = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
KN.fit(X_train, Y_train)


from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(n_estimators = 100, random_state=42)
RFC.fit(X_train, Y_train)


from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier(random_state=42)
DTC.fit(X_train, Y_train)


#https://www.analyticssteps.com/blogs/what-naive-bayes-algorithm-machine-learning
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(X_train, Y_train)


from sklearn import svm
SVM = svm.SVC()
SVM.fit(X_train, Y_train)

SVC()

In [13]:
Y_Pred1 = RFC.predict(X_test)
from sklearn.metrics import confusion_matrix
CM= confusion_matrix(Y_test, Y_Pred1)
CM
#142

array([[96, 27],
       [23, 46]], dtype=int64)

In [14]:
Y_Pred2 = GNB.predict(X_test)
from sklearn.metrics import confusion_matrix
CM= confusion_matrix(Y_test, Y_Pred2)
CM
#141

array([[94, 29],
       [22, 47]], dtype=int64)

In [15]:
Y_Pred3 = LR.predict(X_test)
from sklearn.metrics import confusion_matrix
CM= confusion_matrix(Y_test, Y_Pred3)
CM
#140

array([[95, 28],
       [24, 45]], dtype=int64)

In [16]:
Y_Pred4 = KN.predict(X_test)
from sklearn.metrics import confusion_matrix
CM= confusion_matrix(Y_test, Y_Pred4)
CM
#131

array([[94, 29],
       [32, 37]], dtype=int64)

In [17]:
Y_Pred5 = DTC.predict(X_test)
from sklearn.metrics import confusion_matrix
CM= confusion_matrix(Y_test, Y_Pred5)
CM
#136

array([[87, 36],
       [20, 49]], dtype=int64)

In [18]:
Y_Pred6 = SVM.predict(X_test)
from sklearn.metrics import confusion_matrix
CM= confusion_matrix(Y_test, Y_Pred6)
CM
#141

array([[101,  22],
       [ 30,  39]], dtype=int64)

In [22]:
#Accuracy of Models
print("LR: {}".format(LR.score(X_test, Y_test)))

LR: 0.7291666666666666


In [23]:
print("KN: {}".format(KN.score(X_test, Y_test)))

KN: 0.6822916666666666


In [24]:
print("RFC: {}".format(RFC.score(X_test, Y_test)))

RFC: 0.7395833333333334


In [25]:
print("SVM: {}".format(SVM.score(X_test, Y_test)))

SVM: 0.7291666666666666


In [26]:
print("GNB: {}".format(GNB.score(X_test, Y_test)))

GNB: 0.734375


In [27]:
print("DTC: {}".format(DTC.score(X_test, Y_test)))

DTC: 0.7083333333333334


In [28]:
#RFC>GNB>LR=SVM>DTC>KN- Accuracy of Models Prediction

In [29]:
print("Accuracy:", metrics.accuracy_score(Y_test, Y_Pred1))
print("Precision:", metrics.precision_score(Y_test, Y_Pred1))
print("Recall:", metrics.recall_score(Y_test, Y_Pred1))

Accuracy: 0.7395833333333334
Precision: 0.6301369863013698
Recall: 0.6666666666666666


In [30]:
print("Accuracy:", metrics.accuracy_score(Y_test, Y_Pred2))
print("Precision:", metrics.precision_score(Y_test, Y_Pred2))
print("Recall:", metrics.recall_score(Y_test, Y_Pred2))

Accuracy: 0.734375
Precision: 0.618421052631579
Recall: 0.6811594202898551


In [31]:
print("Accuracy:", metrics.accuracy_score(Y_test, Y_Pred3))
print("Precision:", metrics.precision_score(Y_test, Y_Pred3))
print("Recall:", metrics.recall_score(Y_test, Y_Pred3))

Accuracy: 0.7291666666666666
Precision: 0.6164383561643836
Recall: 0.6521739130434783
