In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [2]:
ti = pd.read_csv("tested.csv")
ti.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.481622    0.841838   14.181209    0.896760   
min     892.000000    0.000000    1.000000    0.170000    0.000000   
25%     996.250000    0.000000    1.000000   21.000000    0.000000   
50%    1100.500000    0.000000    3.000000   27.000000    0.000000   
75%    1204.750000    1.000000    3.000000   39.000000    1.000000   
max    1309.000000    1.000000    3.000000   76.000000    8.000000   

            Parch        Fare  
count  418.000000  417.000000  
mean     0.392344   35.627188  
std      0.981429   55.907576  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.500000  
max      9.000000  512.329200

In [3]:
ti

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [4]:
#ti.replace(np.nan,0)
ti.fillna(ti.mean(),inplace=True)

C:\Users\A\AppData\Local\Temp/ipykernel_11660/1682143471.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  ti.fillna(ti.mean(),inplace=True)


In [5]:
ti.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [6]:
#split dataset in features and target variable
feature_cols = ['PassengerId', 'Pclass', 'Age','SibSp','Parch','Fare'] 
X = ti[feature_cols].values # Features
y = ti.Survived # Target variable

In [7]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

X_train = Data used to train the model

X_test = Data to be tested on X_train model, giving output in form of- y_predicted {Using classifier/regressor}

Now, through loss function, model learns through difference between y_predicted and y_train

Final evaluation of model is done by computing loss between predictions of y_predicted and y_test

In [8]:
X_train

array([[9.0500e+02, 2.0000e+00, 6.3000e+01, 1.0000e+00, 0.0000e+00,
        2.6000e+01],
       [1.0790e+03, 3.0000e+00, 1.7000e+01, 2.0000e+00, 0.0000e+00,
        8.0500e+00],
       [9.5300e+02, 2.0000e+00, 3.2000e+01, 0.0000e+00, 0.0000e+00,
        1.3500e+01],
       ...,
       [1.2880e+03, 3.0000e+00, 2.4000e+01, 0.0000e+00, 0.0000e+00,
        7.2500e+00],
       [1.1270e+03, 3.0000e+00, 2.0000e+01, 0.0000e+00, 0.0000e+00,
        7.8542e+00],
       [9.2900e+02, 3.0000e+00, 2.1000e+01, 0.0000e+00, 0.0000e+00,
        8.6625e+00]])

In [9]:
X_test

array([[1.25000000e+03, 3.00000000e+00, 3.02725904e+01, 0.00000000e+00,
        0.00000000e+00, 7.75000000e+00],
       [1.05600000e+03, 2.00000000e+00, 4.10000000e+01, 0.00000000e+00,
        0.00000000e+00, 1.30000000e+01],
       [9.09000000e+02, 3.00000000e+00, 2.10000000e+01, 0.00000000e+00,
        0.00000000e+00, 7.22500000e+00],
       [9.59000000e+02, 1.00000000e+00, 4.70000000e+01, 0.00000000e+00,
        0.00000000e+00, 4.24000000e+01],
       [8.96000000e+02, 3.00000000e+00, 2.20000000e+01, 1.00000000e+00,
        1.00000000e+00, 1.22875000e+01],
       [1.26900000e+03, 2.00000000e+00, 2.10000000e+01, 0.00000000e+00,
        0.00000000e+00, 1.15000000e+01],
       [1.10600000e+03, 3.00000000e+00, 3.80000000e+01, 4.00000000e+00,
        2.00000000e+00, 7.77500000e+00],
       [1.18200000e+03, 1.00000000e+00, 3.02725904e+01, 0.00000000e+00,
        0.00000000e+00, 3.96000000e+01],
       [1.27300000e+03, 3.00000000e+00, 2.60000000e+01, 0.00000000e+00,
        0.00000000e+00, 

In [10]:
y_train

13     0
187    0
61     0
286    0
405    0
      ..
255    0
72     1
396    0
235    0
37     1
Name: Survived, Length: 313, dtype: int64

In [11]:
y_test

358    0
164    0
17     0
67     0
4      1
      ..
92     1
250    1
117    1
23     0
314    1
Name: Survived, Length: 105, dtype: int64

https://stackoverflow.com/questions/23838056/what-is-the-difference-between-transform-and-fit-transform-in-sklearn

Fit(): Method calculates the parameters μ and σ and saves them as internal objects.

2.Transform(): Method using these calculated parameters apply the transformation to a particular dataset.

3.Fit_transform(): joins the fit() and transform() method for transformation of dataset.

In [12]:
#Phase3
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[-1.58572932, -0.30108824,  2.5502664 ,  0.64504103, -0.38339547,
        -0.20182797],
       [-0.14381544,  0.87691949, -1.06201385,  1.79874299, -0.38339547,
        -0.49739442],
       [-1.18795997, -0.30108824,  0.11590362, -0.50866093, -0.38339547,
        -0.40765419],
       ...,
       [ 1.5881386 ,  0.87691949, -0.51231903, -0.50866093, -0.38339547,
        -0.5105673 ],
       [ 0.25395391,  0.87691949, -0.82643036, -0.50866093, -0.38339547,
        -0.50061848],
       [-1.38684465,  0.87691949, -0.74790253, -0.50866093, -0.38339547,
        -0.48730894]])

In [14]:
X_test

array([[ 1.27323787,  0.87691949, -0.01974611, -0.50866093, -0.38339547,
        -0.50233425],
       [-0.33441325, -0.30108824,  0.82265411, -0.50866093, -0.38339547,
        -0.41588724],
       [-1.55258187,  0.87691949, -0.74790253, -0.50866093, -0.38339547,
        -0.51097895],
       [-1.1382388 , -1.47909596,  1.2938211 , -0.50866093, -0.38339547,
         0.06821603],
       [-1.66031107,  0.87691949, -0.6693747 ,  0.64504103,  0.60836306,
        -0.42761933],
       [ 1.43068823, -0.30108824, -0.74790253, -0.50866093, -0.38339547,
        -0.44058638],
       [ 0.07992982,  0.87691949,  0.58707061,  4.1061469 ,  1.6001216 ,
        -0.5019226 ],
       [ 0.70973129, -1.47909596, -0.01974611, -0.50866093, -0.38339547,
         0.02211096],
       [ 1.46383568,  0.87691949, -0.35526337, -0.50866093, -0.38339547,
        -0.50020683],
       [-1.65202421,  0.87691949, -1.29759735, -0.50866093, -0.38339547,
        -0.47804676],
       [ 1.10750064, -0.30108824, -0.4337912 , -0.

In [15]:
#Using Logistic Regression Algorithm to the Training Set
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, y_train)

#Using KNeighborsClassifier Method of neighbors class to use Nearest Neighbor algorithm
from sklearn.neighbors import KNeighborsClassifier
kNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
kNN.fit(X_train, y_train)

#Using SVC method of svm class to use Support Vector Machine Algorithm
from sklearn.svm import SVC
lsvc = SVC(kernel = 'linear', random_state = 0)
lsvc.fit(X_train, y_train)

#Using SVC method of svm class to use Kernel SVM Algorithm
from sklearn.svm import SVC
rbf = SVC(kernel = 'rbf', random_state = 0)
rbf.fit(X_train, y_train)

#Using GaussianNB method of naïve_bayes class to use Naïve Bayes Algorithm
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

#Using DecisionTreeClassifier of tree class to use Decision Tree Algorithm

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtc.fit(X_train, y_train)

#Using RandomForestClassifier method of ensemble class to use Random Forest Classification algorithm

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [16]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 0)
lr.fit(X_train, y_train)


LogisticRegression(random_state=0)

In [17]:
y_pred = rfc.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[59, 11],
       [25, 10]], dtype=int64)

In [19]:
#test the three models with the test data and print their accuracy scores

#print('classifier: {}'.format(sc.score(X_test, y_test)))
print('lr: {}'.format(lr.score(X_test, y_test)))
print('kNN: {}'.format(kNN.score(X_test, y_test)))
print('lsvc: {}'.format(lsvc.score(X_test, y_test)))
print('rdf: {}'.format(rbf.score(X_test, y_test)))
print('gnbr: {}'.format(gnb.score(X_test, y_test)))
print('dtc: {}'.format(dtc.score(X_test, y_test)))
print('rfc: {}'.format(rfc.score(X_test, y_test)))

lr: 0.6571428571428571
kNN: 0.6761904761904762
lsvc: 0.638095238095238
rdf: 0.6857142857142857
gnbr: 0.7047619047619048
dtc: 0.638095238095238
rfc: 0.6571428571428571


In [20]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.6571428571428571
Precision: 0.47619047619047616
Recall: 0.2857142857142857
